version: '3'
services:
  dev-deploy:
    image: 'tomcat:9'
    ports:
      - '8080:8080'
    volumes:
      - /mnt/war/war:/usr/local/tomcat/webapps
    logging:
      driver: awslogs
      options:
      - awslogs-group: docker-log
      - awslogs-region: ap-south-1
